name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build site with Jekyll
      env:
        JEKYLL_ENV: production
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git checkout -b gh-pages
        git add -f _site
        git commit -m "Deploy site"
        git push -f origin gh-pages
